[package]
edition = "2024"
name = "action"
version = "0.1.0"

[dependencies]
anyhow = "1.0.98"
base64 = "0.22.1"
dotenv = "0.15.0"
futures = "0.3.31"
git2 = "0.20.2"
glob = "0.3.2"
openssl = {version = "0.10.73", features = ["vendored"]}
regex-lite = "0.1.6"
reqwest = {version = "0.12.20", features = ["json"]}
serde = "1.0.219"
serde_json = "1.0.140"
serde_yaml = "0.9.34-deprecated"
time = {version = "0.3.41", features = ["local-offset"]}
tokio = {version = "1.45.1", features = ["rt-multi-thread", "macros"]}
tracing = "0.1.41"
tracing-subscriber = {version = "0.3.19", features = ["time"]}
